services:
  - type: web
    name: keycloak
    env: docker
    plan: free
    buildCommand: ./kc.sh build
    startCommand: ./kc.sh start-dev
    envVars:
      - key: KEYCLOAK_ADMIN
        value: admin
      - key: KEYCLOAK_ADMIN_PASSWORD
        value: admin123
